In [1]:
import pandas as pd
import seaborn as sns
import os
import matplotlib.pyplot as plt
import pylab

## functions to clean index names

In [11]:
# rename index names
def clean_index_names(df, sep): # read in a dataframe and a separator for the index name cleaning
    # get the list of index names
    index_list = list(df.index)
    for name in index_list:
        name_list = name.split(sep)
        n = len(name_list)
    # get the last nonempty item of the name list 
        for i in range (1,n):
            if name_list[-i] != "":
                df.rename(index = {name: name_list[-i]}, inplace=True)
                break
    return df

In [2]:
# set directory
os.chdir('Greywater_Metagemonics/Greywater_Data/')
# define file names 
# use taxonomy data from decontaminated sequence libraries (*_level_number.txt)

# taxa_domain='taxomony_all_level_1.txt'
# taxa_phylum='taxonomy/taxomony_all_level_2.txt'
# taxa_class='taxomony_all_level_3.txt'
# taxa_order='taxomony_all_level_4.txt'
# taxa_family='taxomony_all_level_5.txt'
# taxa_genus='taxomony_all_level_6.txt'

## Metaphlan2 taxonomy ouput data cleaning

In [3]:
# read from txt file
taxa_metaphlan2 = "taxonomy/merged_metaphlan2_taxonomy_relab.txt"
taxa_df = pd.read_csv(taxa_metaphlan2, delimiter = "\t",index_col=0)

In [4]:
taxa_df.head()

,profiled_house_1_raw,profiled_house_1_treat,profiled_house_2_raw,profiled_house_2_treat,profiled_house_3_raw,profiled_house_3_treat,profiled_house_4_raw,profiled_house_4_treat,profiled_house_5_raw,profiled_house_5_treat
ID,,,,,,,,,,
#SampleID,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis,Metaphlan2_Analysis
k__Archaea,0.03128,0.0,1.59189,0.03635,0.02259,0.0,24.7696,0.21723,0.13325,2.53025
k__Archaea|p__Euryarchaeota,0.03128,0.0,1.59189,0.02781,0.02259,0.0,24.7696,0.21723,0.13325,2.53025
k__Archaea|p__Euryarchaeota|c__Methanobacteria,0.0,0.0,0.00399,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales,0.0,0.0,0.00399,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# delete the first row, make data type float
taxa_df = taxa_df.drop(["#SampleID"]).astype(float)

In [6]:
taxa_df.head()

,profiled_house_1_raw,profiled_house_1_treat,profiled_house_2_raw,profiled_house_2_treat,profiled_house_3_raw,profiled_house_3_treat,profiled_house_4_raw,profiled_house_4_treat,profiled_house_5_raw,profiled_house_5_treat
ID,,,,,,,,,,
k__Archaea,0.03128,0.0,1.59189,0.03635,0.02259,0.0,24.7696,0.21723,0.13325,2.53025
k__Archaea|p__Euryarchaeota,0.03128,0.0,1.59189,0.02781,0.02259,0.0,24.7696,0.21723,0.13325,2.53025
k__Archaea|p__Euryarchaeota|c__Methanobacteria,0.00000,0.0,0.00399,0.00000,0.00000,0.0,0.0000,0.00000,0.00000,0.00000
k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales,0.00000,0.0,0.00399,0.00000,0.00000,0.0,0.0000,0.00000,0.00000,0.00000
k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae,0.00000,0.0,0.00399,0.00000,0.00000,0.0,0.0000,0.00000,0.00000,0.00000

### Get only specific level of taxonomy table and remove "p__"
#### Each level will add up to 1

In [107]:
# get the lowest level names
taxa_df = dc.clean_index_names(taxa_df, "|")
taxa_list = list(taxa_df.index)

# get a list of species level taxonomy
sp_list = []
for x in taxa_list: 
    if "s__" in x: 
        sp_list.append(x)

# get a sub dataframe containing only phylum level
sp_df = taxa_df.loc[sp_list]

# get rid of "p__"
for name in list(sp_df.index):
    sp_df.rename(index = {name: name[3:].replace("_"," ")}, inplace = True)

In [109]:
sp_df.head()

,profiled_house_1_raw,profiled_house_1_treat,profiled_house_2_raw,profiled_house_2_treat,profiled_house_3_raw,profiled_house_3_treat,profiled_house_4_raw,profiled_house_4_treat,profiled_house_5_raw,profiled_house_5_treat
ID,,,,,,,,,,
Methanobacterium unclassified,0.00000,0.0,0.00399,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000
Methanoregula formicica,0.00000,0.0,0.00000,0.00000,0.00000,0.0,1.30255,0.00000,0.00000,0.00000
Methanospirillum hungatei,0.02156,0.0,0.67623,0.00439,0.01039,0.0,0.00000,0.00000,0.00000,0.00000
Methanosaeta concilii,0.00000,0.0,0.83834,0.02342,0.00143,0.0,11.44339,0.17617,0.05688,2.46452
Methanosaeta unclassified,0.00000,0.0,0.00000,0.00000,0.01076,0.0,2.82396,0.00000,0.02160,0.00000

In [111]:
for name in sp_df.columns:
    sp_df.rename(columns = {name: name[9:]}, inplace = True)

### Save cleaned data to pickle
#### dataframe: sample IDs as column names, taxonomy (features) as indexes

In [112]:
sp_df.head()

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
ID,,,,,,,,,,
Methanobacterium unclassified,0.00000,0.0,0.00399,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000
Methanoregula formicica,0.00000,0.0,0.00000,0.00000,0.00000,0.0,1.30255,0.00000,0.00000,0.00000
Methanospirillum hungatei,0.02156,0.0,0.67623,0.00439,0.01039,0.0,0.00000,0.00000,0.00000,0.00000
Methanosaeta concilii,0.00000,0.0,0.83834,0.02342,0.00143,0.0,11.44339,0.17617,0.05688,2.46452
Methanosaeta unclassified,0.00000,0.0,0.00000,0.00000,0.01076,0.0,2.82396,0.00000,0.02160,0.00000

In [113]:
sp_df.to_pickle("taxonomy/metaphlan2_species_relab.pkl")

In [61]:
# search microorganisms:
search = "Pseudomonas"

result = [i for i in list(sp_df.index) if i.startswith(search)]
print(result)

['Pseudomonas aeruginosa', 'Pseudomonas alcaligenes', 'Pseudomonas alcaliphila', 'Pseudomonas amygdali', 'Pseudomonas entomophila', 'Pseudomonas fragi', 'Pseudomonas mandelii', 'Pseudomonas mendocina', 'Pseudomonas nitroreducens', 'Pseudomonas protegens', 'Pseudomonas putida', 'Pseudomonas stutzeri', 'Pseudomonas unclassified']

#### Get genus level data

In [8]:
# get the lowest level names
taxa_df = clean_index_names(taxa_df, "|")
taxa_list = list(taxa_df.index)

# get a list of genus level taxonomy
genus_list = []
for x in taxa_list: 
    if "g__" in x: 
        genus_list.append(x)

# get a sub dataframe containing only phylum level
genus_df = taxa_df.loc[genus_list]

# get rid of "p__"
for name in list(genus_df.index):
    genus_df.rename(index = {name: name[3:].replace("_"," ")}, inplace = True)

In [10]:
genus_df.head()

,profiled_house_1_raw,profiled_house_1_treat,profiled_house_2_raw,profiled_house_2_treat,profiled_house_3_raw,profiled_house_3_treat,profiled_house_4_raw,profiled_house_4_treat,profiled_house_5_raw,profiled_house_5_treat
ID,,,,,,,,,,
Methanobacterium,0.00000,0.0,0.00399,0.00000,0.00000,0.0,0.00000,0.00000,0.00000,0.00000
Methanoregula,0.00000,0.0,0.00000,0.00000,0.00000,0.0,1.30255,0.00000,0.00000,0.00000
Methanoregulaceae unclassified,0.00972,0.0,0.00000,0.00000,0.00000,0.0,9.19970,0.04106,0.05477,0.06573
Methanospirillum,0.02156,0.0,0.67623,0.00439,0.01039,0.0,0.00000,0.00000,0.00000,0.00000
Methanosaeta,0.00000,0.0,0.83834,0.02342,0.01220,0.0,14.26735,0.17617,0.07848,2.46452

In [12]:
for name in genus_df.columns:
    genus_df.rename(columns = {name: name[9:]}, inplace = True)

In [14]:
genus_df.to_csv("taxonomy/metaphlan2_genus_relab_all.txt", sep = "\t")

## Metaxa2 taxonomy output cleaning

### Get mapped read numbers for each sample

In [3]:
# read in metaxa2 reads numbers from file, each line is [sample ID]: [reads]
reads = "taxonomy/reads_summary.txt"
# construct a dictionary of sample:reads.
reads_dict = {}
with open(reads, "r") as f: 
    for line in f.readlines():
        col = line.split(":")
        reads_dict[col[0]] = int(col[1])

### Save reads to a dataframe

In [5]:
# save metaxa2 reads for each sample in dataframe pkl
# reads_df = pd.DataFrame(reads_dict, index = ["reads"])
# reads_df.to_pickle("taxonomy/metaxa2_reads.pkl")

In [4]:
reads_dict

{'house_1_raw': 51188,
 'house_1_treat': 29339,
 'house_2_raw': 52100,
 'house_2_treat': 46626,
 'house_3_raw': 82383,
 'house_3_treat': 23308,
 'house_4_raw': 33596,
 'house_4_treat': 51416,
 'house_5_raw': 36656,
 'house_5_treat': 17580}

### Get metaxa2 taxonomy output for a level

In [62]:
taxa_phylum='taxonomy/taxomony_all_level_2.txt'
taxa_genus='taxonomy/taxomony_all_level_6.txt'
taxa_species='taxonomy/taxomony_all_level_7.txt'
taxa_family='taxonomy/taxomony_all_level_5.txt'
taxa_df = pd.read_csv(taxa_phylum, delimiter = "\t",index_col=0)
print(taxa_df.shape)

(52, 10)

In [63]:
taxa_df.head(2)

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
Taxa,,,,,,,,,,
Archaea;Crenarchaeota,0,0,0,2,0,0,2,1,0,0
Archaea;Euryarchaeota,23,47,131,103,9,64,1552,11,2,13

In [64]:
# filter out taxa with 0 or 1 reads
taxa_filter = taxa_df[taxa_df > 1]
taxa_filter

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
Taxa,,,,,,,,,,
Archaea;Crenarchaeota,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN
Archaea;Euryarchaeota,23.0,47.0,131.0,103.0,9.0,64.0,1552.0,11.0,2.0,13.0
Archaea;Thaumarchaeota,NaN,170.0,NaN,27.0,NaN,2.0,NaN,NaN,NaN,2.0
Archaea;Unclassified Archaea,NaN,14.0,NaN,21.0,NaN,19.0,NaN,NaN,NaN,NaN
Bacteria;Acidobacteria,38.0,136.0,83.0,101.0,NaN,98.0,195.0,11.0,73.0,126.0
Bacteria;Actinobacteria,41.0,1180.0,255.0,753.0,86.0,995.0,100.0,257.0,4.0,261.0
Bacteria;Aquificae,NaN,67.0,2.0,14.0,NaN,7.0,11.0,7.0,NaN,18.0
Bacteria;Armatimonadetes,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
Bacteria;BD1-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bacteria;Bacteroidetes,1421.0,3021.0,15564.0,4209.0,1634.0,2630.0,2227.0,776.0,1640.0,813.0
Bacteria;Candidate division TM7,8.0,209.0,146.0,167.0,17.0,482.0,20.0,195.0,NaN,90.0
Bacteria;Candidate division WS6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bacteria;Chlamydiae,NaN,747.0,13.0,362.0,NaN,332.0,26.0,73.0,2.0,593.0
Bacteria;Chlorobi,NaN,19.0,63.0,8.0,NaN,9.0,2.0,2.0,NaN,9.0
Bacteria;Chloroflexi,NaN,237.0,204.0,67.0,30.0,146.0,84.0,28.0,NaN,47.0
Bacteria;Chrysiogenetes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bacteria;Cyanobacteria,6.0,132.0,60.0,90.0,NaN,145.0,31.0,32.0,NaN,20.0
Bacteria;Deferribacteres,27.0,3.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
Bacteria;Deinococcus-Thermus,NaN,86.0,8.0,24.0,NaN,35.0,2.0,4.0,NaN,15.0
Bacteria;Dictyoglomi,NaN,6.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
Bacteria;Elusimicrobia,7.0,12.0,44.0,NaN,NaN,3.0,5.0,NaN,NaN,NaN
Bacteria;Fibrobacteres,NaN,17.0,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
Bacteria;Firmicutes,435.0,749.0,13199.0,686.0,1248.0,712.0,744.0,231.0,182.0,246.0
Bacteria;Fusobacteria,6.0,10.0,19.0,NaN,NaN,17.0,3.0,22.0,NaN,2.0
Bacteria;Gemmatimonadetes,NaN,14.0,NaN,7.0,NaN,6.0,NaN,2.0,NaN,4.0
Bacteria;Lentisphaerae,NaN,NaN,41.0,5.0,NaN,NaN,NaN,3.0,NaN,3.0
Bacteria;Nitrospirae,NaN,26.0,4.0,40.0,NaN,29.0,NaN,2.0,NaN,7.0
Bacteria;Planctomycetes,2.0,460.0,39.0,379.0,NaN,535.0,19.0,135.0,NaN,316.0
Bacteria;Proteobacteria,48636.0,14203.0,17818.0,34049.0,78646.0,10305.0,26249.0,25763.0,34544.0,10188.0
Bacteria;Spirochaetes,19.0,29.0,181.0,9.0,2.0,19.0,56.0,11.0,NaN,8.0
Bacteria;Synergistetes,70.0,7.0,561.0,17.0,13.0,3.0,46.0,3.0,NaN,7.0
Bacteria;Tenericutes,NaN,235.0,63.0,115.0,NaN,167.0,5.0,46.0,NaN,36.0
Bacteria;Thermodesulfobacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bacteria;Thermotogae,NaN,27.0,NaN,3.0,NaN,14.0,2.0,6.0,NaN,8.0
Bacteria;Unclassified Bacteria,358.0,4020.0,3215.0,1994.0,555.0,3920.0,1722.0,1008.0,191.0,1665.0
Bacteria;Verrucomicrobia,73.0,293.0,102.0,253.0,4.0,439.0,165.0,34.0,3.0,149.0
Chloroplast;,NaN,NaN,NaN,4.0,NaN,NaN,NaN,3.0,NaN,NaN
Chloroplast;Unclassified Chloroplast,NaN,80.0,3.0,72.0,NaN,109.0,6.0,870.0,NaN,20.0
Eukaryota;Alveolata,NaN,50.0,17.0,755.0,NaN,30.0,109.0,828.0,NaN,123.0
Eukaryota;Archaeplastida,NaN,NaN,2.0,179.0,NaN,2.0,NaN,10.0,NaN,NaN
Eukaryota;Chromalveolata,2.0,58.0,NaN,343.0,NaN,344.0,12.0,12722.0,3.0,43.0
Eukaryota;Excavata,NaN,11.0,5.0,85.0,NaN,13.0,5.0,432.0,NaN,6.0
Eukaryota;Fungi,2.0,161.0,10.0,180.0,NaN,23.0,5.0,264.0,NaN,168.0
Eukaryota;Metazoa,NaN,1658.0,9.0,499.0,120.0,213.0,39.0,157.0,NaN,1936.0
Eukaryota;Rhizaria,NaN,28.0,3.0,42.0,NaN,24.0,4.0,1329.0,NaN,71.0
Eukaryota;Unclassified Eukaryota,NaN,116.0,32.0,206.0,3.0,317.0,23.0,995.0,NaN,150.0
Eukaryota;Unikonta,NaN,12.0,NaN,11.0,NaN,20.0,3.0,87.0,NaN,16.0
Eukaryota;Viridiplantae,NaN,NaN,NaN,40.0,NaN,NaN,3.0,5.0,NaN,NaN
Mitochondria;,NaN,8.0,NaN,11.0,NaN,NaN,NaN,3.0,NaN,NaN
Mitochondria;Unclassified Mitochondria,NaN,74.0,NaN,43.0,4.0,30.0,8.0,967.0,NaN,19.0
Unclassified ;,6.0,823.0,172.0,543.0,6.0,949.0,103.0,3618.0,5.0,350.0
Unknown;,2.0,78.0,15.0,96.0,3.0,85.0,6.0,461.0,NaN,28.0

In [65]:
# filter out all NaN genus
taxa_filter = taxa_filter.dropna(axis = 0, thresh = 1).fillna(value=0)

In [66]:
print(taxa_filter.shape)
taxa_filter

(48, 10)

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
Taxa,,,,,,,,,,
Archaea;Crenarchaeota,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0
Archaea;Euryarchaeota,23.0,47.0,131.0,103.0,9.0,64.0,1552.0,11.0,2.0,13.0
Archaea;Thaumarchaeota,0.0,170.0,0.0,27.0,0.0,2.0,0.0,0.0,0.0,2.0
Archaea;Unclassified Archaea,0.0,14.0,0.0,21.0,0.0,19.0,0.0,0.0,0.0,0.0
Bacteria;Acidobacteria,38.0,136.0,83.0,101.0,0.0,98.0,195.0,11.0,73.0,126.0
Bacteria;Actinobacteria,41.0,1180.0,255.0,753.0,86.0,995.0,100.0,257.0,4.0,261.0
Bacteria;Aquificae,0.0,67.0,2.0,14.0,0.0,7.0,11.0,7.0,0.0,18.0
Bacteria;Armatimonadetes,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0
Bacteria;Bacteroidetes,1421.0,3021.0,15564.0,4209.0,1634.0,2630.0,2227.0,776.0,1640.0,813.0
Bacteria;Candidate division TM7,8.0,209.0,146.0,167.0,17.0,482.0,20.0,195.0,0.0,90.0
Bacteria;Chlamydiae,0.0,747.0,13.0,362.0,0.0,332.0,26.0,73.0,2.0,593.0
Bacteria;Chlorobi,0.0,19.0,63.0,8.0,0.0,9.0,2.0,2.0,0.0,9.0
Bacteria;Chloroflexi,0.0,237.0,204.0,67.0,30.0,146.0,84.0,28.0,0.0,47.0
Bacteria;Cyanobacteria,6.0,132.0,60.0,90.0,0.0,145.0,31.0,32.0,0.0,20.0
Bacteria;Deferribacteres,27.0,3.0,12.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
Bacteria;Deinococcus-Thermus,0.0,86.0,8.0,24.0,0.0,35.0,2.0,4.0,0.0,15.0
Bacteria;Dictyoglomi,0.0,6.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
Bacteria;Elusimicrobia,7.0,12.0,44.0,0.0,0.0,3.0,5.0,0.0,0.0,0.0
Bacteria;Fibrobacteres,0.0,17.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
Bacteria;Firmicutes,435.0,749.0,13199.0,686.0,1248.0,712.0,744.0,231.0,182.0,246.0
Bacteria;Fusobacteria,6.0,10.0,19.0,0.0,0.0,17.0,3.0,22.0,0.0,2.0
Bacteria;Gemmatimonadetes,0.0,14.0,0.0,7.0,0.0,6.0,0.0,2.0,0.0,4.0
Bacteria;Lentisphaerae,0.0,0.0,41.0,5.0,0.0,0.0,0.0,3.0,0.0,3.0
Bacteria;Nitrospirae,0.0,26.0,4.0,40.0,0.0,29.0,0.0,2.0,0.0,7.0
Bacteria;Planctomycetes,2.0,460.0,39.0,379.0,0.0,535.0,19.0,135.0,0.0,316.0
Bacteria;Proteobacteria,48636.0,14203.0,17818.0,34049.0,78646.0,10305.0,26249.0,25763.0,34544.0,10188.0
Bacteria;Spirochaetes,19.0,29.0,181.0,9.0,2.0,19.0,56.0,11.0,0.0,8.0
Bacteria;Synergistetes,70.0,7.0,561.0,17.0,13.0,3.0,46.0,3.0,0.0,7.0
Bacteria;Tenericutes,0.0,235.0,63.0,115.0,0.0,167.0,5.0,46.0,0.0,36.0
Bacteria;Thermotogae,0.0,27.0,0.0,3.0,0.0,14.0,2.0,6.0,0.0,8.0
Bacteria;Unclassified Bacteria,358.0,4020.0,3215.0,1994.0,555.0,3920.0,1722.0,1008.0,191.0,1665.0
Bacteria;Verrucomicrobia,73.0,293.0,102.0,253.0,4.0,439.0,165.0,34.0,3.0,149.0
Chloroplast;,0.0,0.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0
Chloroplast;Unclassified Chloroplast,0.0,80.0,3.0,72.0,0.0,109.0,6.0,870.0,0.0,20.0
Eukaryota;Alveolata,0.0,50.0,17.0,755.0,0.0,30.0,109.0,828.0,0.0,123.0
Eukaryota;Archaeplastida,0.0,0.0,2.0,179.0,0.0,2.0,0.0,10.0,0.0,0.0
Eukaryota;Chromalveolata,2.0,58.0,0.0,343.0,0.0,344.0,12.0,12722.0,3.0,43.0
Eukaryota;Excavata,0.0,11.0,5.0,85.0,0.0,13.0,5.0,432.0,0.0,6.0
Eukaryota;Fungi,2.0,161.0,10.0,180.0,0.0,23.0,5.0,264.0,0.0,168.0
Eukaryota;Metazoa,0.0,1658.0,9.0,499.0,120.0,213.0,39.0,157.0,0.0,1936.0
Eukaryota;Rhizaria,0.0,28.0,3.0,42.0,0.0,24.0,4.0,1329.0,0.0,71.0
Eukaryota;Unclassified Eukaryota,0.0,116.0,32.0,206.0,3.0,317.0,23.0,995.0,0.0,150.0
Eukaryota;Unikonta,0.0,12.0,0.0,11.0,0.0,20.0,3.0,87.0,0.0,16.0
Eukaryota;Viridiplantae,0.0,0.0,0.0,40.0,0.0,0.0,3.0,5.0,0.0,0.0
Mitochondria;,0.0,8.0,0.0,11.0,0.0,0.0,0.0,3.0,0.0,0.0
Mitochondria;Unclassified Mitochondria,0.0,74.0,0.0,43.0,4.0,30.0,8.0,967.0,0.0,19.0
Unclassified ;,6.0,823.0,172.0,543.0,6.0,949.0,103.0,3618.0,5.0,350.0
Unknown;,2.0,78.0,15.0,96.0,3.0,85.0,6.0,461.0,0.0,28.0

In [45]:
# normalize by metaxa2 reads numbers
taxa_relab_df = taxa_filter.copy()
for sample in reads_dict.keys():
    taxa_relab_df[sample] = taxa_filter[sample]/taxa_filter[sample].sum()  # or /reads_dict[sample]
    print(taxa_relab_df[sample].sum())
taxa_relab_df.head(2)

1.0
1.0
0.9999999999999999
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
1.0

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
Taxa,,,,,,,,,,
Archaea;Crenarchaeota,0.000000,0.000000,0.000000,0.000043,0.000000,0.000000,0.000060,0.000000,0.000000,0.00000
Archaea;Euryarchaeota,0.000449,0.001602,0.002515,0.002209,0.000109,0.002746,0.046199,0.000214,0.000055,0.00074

### Clean index names

In [67]:
#taxa_relab_clean = clean_index_names(taxa_relab_df, ";")
taxa_filter_clean = clean_index_names(taxa_filter, ";")

In [68]:
taxa_filter_clean.head(2)

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
Taxa,,,,,,,,,,
Crenarchaeota,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0
Euryarchaeota,23.0,47.0,131.0,103.0,9.0,64.0,1552.0,11.0,2.0,13.0

In [69]:
taxa_filter_clean.shape

(48, 10)

In [70]:
# collapse by index
taxa_filter_nodup = taxa_filter_clean.groupby(by="Taxa").sum()
taxa_filter_nodup.to_csv("taxonomy/metaxa2_phylum_counts_filtered01_noduplicate.csv")
taxa_filter_nodup.sample(3)

,house_1_raw,house_1_treat,house_2_raw,house_2_treat,house_3_raw,house_3_treat,house_4_raw,house_4_treat,house_5_raw,house_5_treat
Taxa,,,,,,,,,,
Deinococcus-Thermus,0.0,86.0,8.0,24.0,0.0,35.0,2.0,4.0,0.0,15.0
Fibrobacteres,0.0,17.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
Gemmatimonadetes,0.0,14.0,0.0,7.0,0.0,6.0,0.0,2.0,0.0,4.0

### Save dataframe to csv: sample IDs as column names, taxonomy(features) as index.

In [11]:
# save dataframe to csv
# taxa_relab_clean.to_csv("taxonomy/metaxa2_phylum_relab_filtered01.csv")
taxa_filter_clean.to_csv("taxonomy/metaxa2_genus_counts_filtered01.csv")